### ISSUE TITLE
Docker deployment

### ISSUE THREAD

**Issue by sepastian** [sgsinclair/VoyantServer#14]
First of all, thanks for developing Voyant, its a great tool! I am creating a `Dockerfile` for the latest release of VoyantServer. Unfortunately, I am running into an issue when the voyant app gets deployed during Tomcat startup. Do you know what the problem could be?

```
05-Dec-2016 11:17:44.273 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/voyant
05-Dec-2016 11:17:59.918 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/voyant]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsupportedClassVersionError: org/voyanttools/trombone/storage/Storage : Unsupported major.minor version 52.0 (unable to load class org.voyanttools.trombone.storage.Storage)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2561)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:859)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1302)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2509)
	at java.lang.Class.getDeclaredFields(Class.java:1819)
	at org.apache.catalina.util.Introspection.getDeclaredFields(Introspection.java:106)
	at org.apache.catalina.startup.WebAnnotationSet.loadFieldsAnnotation(WebAnnotationSet.java:256)
	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationServletAnnotations(WebAnnotationSet.java:132)
	at org.apache.catalina.startup.WebAnnotationSet.loadApplicationAnnotations(WebAnnotationSet.java:65)
	at org.apache.catalina.startup.ContextConfig.applicationAnnotationsConfig(ContextConfig.java:336)
	at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:786)
	at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5213)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	... 10 more
05-Dec-2016 11:17:59.922 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory /usr/local/tomcat/webapps/voyant
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/voyant]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:757)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
05-Dec-2016 11:17:59.923 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/voyant has finished in 15,650 ms
```

**Comment by sgsinclair** [comment]
The first thing I'd check is if you're running Java 1.8+

**Comment by sepastian** [comment]
Hi, thanks for your reply. I did some research and came to the same conclusion. I switched to `tomcat:7-jre8`, its working now.

I made the Docker image public, if anyone is interested: https://hub.docker.com/r/sepastian/voyant-docker/. (The one from dariah is quite out-of-date.)

Closing this, thanks!

**Comment by sgsinclair** [comment]
Thanks to you! Not sure if/what your twitter handle is, but https://twitter.com/VoyantTools/status/805785108724781056

**Comment by sepastian** [comment]
:+1:

**Comment by triplingual** [comment]
Thanks for making this container. Might be just what I needed as a comprehensible way for me to learn Docker. Your command for installing at https://hub.docker.com/r/sepastian/voyant-docker/ seems to have a mistake, though. Looks like command should be
`$ docker run -d --name voyant -p 8080:8080 sepastian/voyant-docker:latest`
rather than
`$ docker run -d --name voyant -p 8080:8080 sepastian/voyant:latest`
as it is now. Or at least the former is what ran for me when the latter failed.

**Comment by triplingual** [comment]
Also (apologies for the drip drip drip), the URL to address should be `http://localhost:8080/voyant/` rather than `http://localhost:8080/`, just for those of us too thick to figure that out without a touch of assistance or experience with Voyant. :-)

**Comment by sepastian** [comment]
Updated, thanks. Take a look, if you like, so everything looks OK.
