### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by cdigenna** [sgsinclair/VoyantServer#31]
Hi, 

I am running Java 1.8 and just installed Voyant Server and get the below output from the console each time I open the .jar file. The app opens, but the browser does not, and the /8888 path leads to an error when pasted in the browser. 

Thanks! 

*** Starting Voyant Server – Web page will open automatically when ready ***

Using Free AdminPort=34000
Server Starting
2019-08-21 15:53:15.933:INFO::main: Logging initialized @125ms
Jetty Version: 9.3.z-SNAPSHOT
http://*:8888
Jetty starting up ... please wait
2019-08-21 15:53:15.999:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2019-08-21 15:53:19.609:WARN:oejut.QueuedThreadPool:qtp29832506-15: 
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:617)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.609:WARN:oejut.QueuedThreadPool:qtp29832506-17: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-15: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=10<=200,i=0,q=2}
2019-08-21 15:53:19.609:WARN:oejut.QueuedThreadPool:qtp29832506-16: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.609:WARN:oejut.QueuedThreadPool:qtp29832506-12: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-16: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=9<=200,i=0,q=3}
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-17: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=10<=200,i=0,q=2}
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-19: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.619:WARN:oejut.QueuedThreadPool:qtp29832506-20: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.611:WARN:oejut.QueuedThreadPool:qtp29832506-13: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-11: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:19.610:WARN:oejut.QueuedThreadPool:qtp29832506-12: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=9<=200,i=0,q=3}
2019-08-21 15:53:19.609:WARN:oejut.QueuedThreadPool:qtp29832506-14: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
Exception in thread "qtp29832506-15" 2019-08-21 15:53:19.635:WARN:oejut.QueuedThreadPool:qtp29832506-11: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=7<=200,i=0,q=6}
2019-08-21 15:53:19.635:WARN:oejut.QueuedThreadPool:qtp29832506-14: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=7<=200,i=0,q=6}
Exception in thread "qtp29832506-12" 2019-08-21 15:53:19.621:WARN:oejut.QueuedThreadPool:qtp29832506-13: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=8<=200,i=0,q=6}
2019-08-21 15:53:19.621:WARN:oejut.QueuedThreadPool:qtp29832506-20: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=8<=200,i=0,q=6}
Exception in thread "qtp29832506-17" 2019-08-21 15:53:19.621:WARN:oejut.QueuedThreadPool:qtp29832506-19: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=9<=200,i=0,q=6}
Exception in thread "qtp29832506-16" Exception in thread "qtp29832506-13" Exception in thread "qtp29832506-11" Exception in thread "qtp29832506-20" Exception in thread "qtp29832506-14" Exception in thread "qtp29832506-19" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:20.538:WARN:oejut.QueuedThreadPool:qtp29832506-10: 
java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:1003)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:984)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:933)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:851)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:548)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Unknown Source)
2019-08-21 15:53:20.539:WARN:oejut.QueuedThreadPool:qtp29832506-10: Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@f5c692 in qtp29832506{STARTED,8<=1<=200,i=0,q=7}
Exception in thread "qtp29832506-10" java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Unknown Source)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.startThreads(QueuedThreadPool.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.access$200(QueuedThreadPool.java:47)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:639)
	at java.lang.Thread.run(Unknown Source)

**Comment by cdigenna** [comment]
Edit: Solved by installing 64-bit Java.

**Comment by sgsinclair** [comment]
Thanks for offering this solution. Another solution is to edit the settings file to allocate less memory at start up (like 256 or 512), but with recent machines having increased memory this is less often an issue.
